name: club_dj
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  geolocator: ^8.0.1
  # get: ^4.6.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  pinput: ^3.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
