// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIKPZACaLHNF3NypHjgIScRwRhpuiOOk',
    appId: '1:1082350793346:web:a699905bf9db8778b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    authDomain: 'club-f0ffa.firebaseapp.com',
    databaseURL: 'https://club-f0ffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'club-f0ffa.appspot.com',
    measurementId: 'G-MYKPRV83EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdk8LUM4zzTrys5V4YwXqniLgcGmy-bDA',
    appId: '1:1082350793346:android:9b6cb908d76f8d91b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    databaseURL: 'https://club-f0ffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'club-f0ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5tZm5wTSpLSWRLqwtfiih1osfURUx49g',
    appId: '1:1082350793346:ios:24c67de1d03c3687b03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    databaseURL: 'https://club-f0ffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'club-f0ffa.appspot.com',
    androidClientId: '1082350793346-j6k8k71k21u5gpt4299sfukdk4hg7r98.apps.googleusercontent.com',
    iosClientId: '1082350793346-gffpihjlt9eg2iodrl8258hpkvk7r5pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubDj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5tZm5wTSpLSWRLqwtfiih1osfURUx49g',
    appId: '1:1082350793346:ios:5f7ca3ac0dcac8cbb03a9b',
    messagingSenderId: '1082350793346',
    projectId: 'club-f0ffa',
    databaseURL: 'https://club-f0ffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'club-f0ffa.appspot.com',
    androidClientId: '1082350793346-j6k8k71k21u5gpt4299sfukdk4hg7r98.apps.googleusercontent.com',
    iosClientId: '1082350793346-vatbe4pflahooqup8ko77k2kfeuhqgnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubDj.RunnerTests',
  );
}
